### ISSUE TITLE
Should we make some functions in Optalg class friends to candidate class?

### ISSUE THREAD

**Issue by PanPalitta** [PanPalitta/phase_estimation#16]
Right now when an object of optalg class wants to access the memory in a candidate object, a read function from the candidate object needs to be called and the memory copied. The advantage of this is the safeguard of the memory, but I suspect this might cause cumulative overhead. Allowing the optalg object to access the memory directly might reduce this, but I don't know if this is a good idea.

**Comment by peterwittek** [comment]
The candidate.h file completely escaped my attention until now. There are lots of things to do:

1. We do not need the templated stuff anymore. 
  
2. We should separate the code to a matching cpp from the header.
  
3. Those for loops for copying structure are deeply wrong. Replace them with proper memcpy calls as in update_cont.
  
4. You are right, most of these memory copies can be eliminated entirely, while some of them could be replaced by swapping pointers, but it requires rewriting code in mpi_de.cpp and mpi_pso.cpp. This will surely reduce memory fragmentation.

**Comment by peterwittek** [comment]
In `OptAlg::Cont_fitness`:
  
  - `read_cont` can be replaced by a direct access to the pointer.
  - `write_contfit` should be rewritten. While I would keep the memory copy here, the division could be done in the for loop before in `OptAlg::Cont_fitness`. Alternatively, you can give direct access to the array in candidate, eliminating fit1 array, but you will still need fit2.

In `OptAlg::Best_fitness`, you can give direct access to the arrays, no need for memory copies. You can eliminate both the soln and the fit arrays.

Based on `OptAlg::Final_select`, I think `read_global` should remain a memory copy. Perhaps all reads that perform a copy should be renamed as copy_whatever. Because, for instance, in `OptAlg::avg_Final_select`, instead of `read_global` memory copies, it is perfectly safe to pass the pointer, and you can eliminate the array variable (which, by the way, is a deeply wrong name for a variable).

In `DE::combination`:

  - Eliminate  `double can[this->num];`
  - Send `pop[int(p / nb_proc)].can_best` directly.
  - Rewrite the create donor loop:
  
```
for(i = 0; i < this->num; ++i) {
  //cross-over
  coin = double(rand()) / RAND_MAX;
  if(coin <= Cr || i == rand() % this->num) {
  //create donor
      input[i] = all_soln[fam[0]][i] + F * (all_soln[fam[1]][i] - all_soln[fam[2]][i]);
      }
  else {
      input[i] = all_soln[p][i];
      }
  }
//send the new candidate back
MPI_Send(&input, this->num, MPI_DOUBLE, p % nb_proc, tag, MPI_COMM_WORLD);

```

  - On the receiving side, do something similar. The update_cont memory copy remains necessary, which is also obvious if you study `OptAlg::Init_population` and `OptAlg::Init_previous`.

If you do the above, you can do a simple pointer swap in `update_best` and in `put_to_global` instead of the memory copies. The PSO algorithm will also have to be updated in a similar fashion.

On an unrelated note, perhaps the pop array should be deleted before allocating a new in `OptAlg::Init_previous`. It should also be deleted in the destructors of the optimization algorithms.

**Comment by PanPalitta** [comment]
I have implemented most of your suggestions but there are some that need more consideration than I can give it this week.

Changes not yet implemented are:
1.MPI_Send using pop[].can_best pointer. I have to figure how class work with inheritance.
2.Swapping pointer in update_best and put_to_global. Make sure the memory will not get override later when contender or can_best are updated.
3. Updating PSO algorithm.
4. Deleting pop array without causing error.

**Comment by PanPalitta** [comment]
Updates on this issue:

1. Pop array is now deleted in the destructor of the mpi_optalg class.
2. Swapping pointers is implemented in update_best. This trick does not work for put_to_global since can_best info is used later.
3. Accessing pointers in candidate object cannot be done using DE class since friendship is not inherited. (I still don't know how to deal with this without adding more and more friend classes into candidate class definition directly.)
4. mpi_pso.cpp has been debugged, but none of the operations involving candidate class members has been changed.

**Comment by peterwittek** [comment]
So what else is missing to close this issue?

**Comment by PanPalitta** [comment]
I left it open just in case there is a work around on the issue with friendship and inheritance. We can close this issue if you don't think we need to work on it any further.

**Comment by peterwittek** [comment]
I think this is fine, we can just add the two optimization child classes as friends. Sometimes it pays off to keep it simple, so please close this issue.
